
[milestones]
	#Number of hearts you start out with.
	#Range: 0 ~ 1000
	baseHearts = 10
	#Number of hearts you gain for reaching a new milestone.
	#Range: 0 ~ 1000
	heartsPerMilestone = 1
	#A list of numbers of unique foods you need to eat to unlock each milestone, in ascending order. Naturally, adding more milestones lets you earn more hearts.
	milestones = [5, 10, 15, 20, 25, 30, 40, 50, 60, 70, 90, 110, 130, 150, 170, 200, 230, 260, 290, 320]

[filtering]
	#Foods in this list won't affect the player's health nor show up in the food book.
	blacklist = ["undead_revamp2:fizzysnowgoo",
				"undead_revamp2:huntereye",	
				"undead_revamp2:spiiterfriedegg",
				"apocalypsenow:tomato",
				"apocalypsenow:butter",
				"apocalypsenow:canteen_41",
				"apocalypsenow:canteen_42",
				"apocalypsenow:canteen_43",
				"apocalypsenow:canteen_44",
				"apocalypsenow:chicken_wing",
				"apocalypsenow:cooked_chicken_wing",
				"apocalypsenow:corn",
				"apocalypsenow:cheese",
				"apocalypsenow:marmalade",
				"apocalypsenow:vitamins",
				"apocalypsenow:contaminated_water",
				"apocalypsenow:cooked_canned_chilie",
				"apocalypsenow:cooked_canned_food",
				"apocalypsenow:cooked_canned_soup",
				"apocalypsenow:cooked_canned_beens",
				"apocalypsenow:open_canned_chili",
				"apocalypsenow:open_canned_corn",
				"apocalypsenow:open_canned_soup",
				"apocalypsenow:open_canned_food",
				"apocalypsenow:open_canned_beens",
				"apocalypsenow:open_dogs_food",
				"apocalypsenow:water",
				"apocalypsenow:orange",
				"apocalypsenow:tomato",
				"apocalypsenow:lettuce",
				"apocalypsenow:fried_egg",
				"apocalypsenow:hamburger",
				"apocalypsenow:dead_rat",
				"apocalypsenow:dead_cockroach",
				"apocalypsenow:cooked_rat",
				"apocalypsenow:cooked_cockroach",
				"apocalypsenow:large_soda",
				"spore:biomass",
				"spore:brain_noodles",
				"spore:fiber_stew",
				"spore:heart_kebab",
				"spore:milky_sack",
				"spore:roasted_heart_kebab",
				"spore:roasted_tumor",
				"spore:sausage",
				"spore:vigil_eye_soup",
				"undead_revamp2:clogggerribswithbun",
				"undead_revamp2:cloogerribs",
				"undead_revamp2:spittea",
				"zombie_extreme:canned_apples",
				"zombie_extreme:canned_beans",
				"zombie_extreme:canned_food",
				"zombie_extreme:canned_fruit",
				"zombie_extreme:canned_soup",
				"zombie_extreme:canned_stew",
				"zombie_extreme:cat_food",
				"zombie_extreme:chips",
				"zombie_extreme:dog_food",
				"zombie_extreme:green_apple",
				"zombie_extreme:rotten_apple",
				"zombie_extreme:soda",
				"artifacts:eternal_steak",
				"artifacts:everlasting_beef"]
	#When this list contains anything, the blacklist is ignored and instead only foods from here count.
	whitelist = []
	#The minimum hunger value foods need to provide in order to count for milestones, in half drumsticks.
	#Range: 0 ~ 1000
	minimumFoodValue = 1

[miscellaneous]
	#Whether or not to reset the food list on death, effectively losing all bonus hearts.
	resetOnDeath = false
	#If true, eating foods outside of survival mode (e.g. creative/adventure) is not tracked and thus does not contribute towards progression.
	limitProgressionToSurvival = false

