
#Gamerules that are set when a world is loaded
[gamerules]

	#Modded gamerules
	#The modded gamerules should be populated after loading the game, only integer and boolean values are valid
	[gamerules.modded]

		[gamerules.modded.player]

			[gamerules.modded.player.artifacts]

				[gamerules.modded.player.artifacts.anglersHat]
					luckOfTheSeaLevelBonus = 1
					lureLevelBonus = 1

				[gamerules.modded.player.artifacts.antidoteVessel]
					enabled = true
					maxEffectDuration = 5

				[gamerules.modded.player.artifacts.aquaDashers]
					enabled = true

				[gamerules.modded.player.artifacts.bunnyHoppers]
					doCancelFallDamage = false
					jumpBoostLevel = 2

				[gamerules.modded.player.artifacts.charmOfSinking]
					enabled = true

				[gamerules.modded.player.artifacts.chorusTotem]
					cooldown = 0
					doConsumeOnUse = true
					healthRestored = 10
					teleportationChance = 100

				[gamerules.modded.player.artifacts.cloudInABottle]
					enabled = true
					sprintJumpHorizontalVelocity = 25
					sprintJumpVerticalVelocity = 25

				[gamerules.modded.player.artifacts.cowboyHat]
					speedLevel = 2

				[gamerules.modded.player.artifacts.crossNecklace]
					bonusInvincibilityTicks = 20
					cooldown = 0

				[gamerules.modded.player.artifacts.crystalHeart]
					healthBonus = 10

				[gamerules.modded.player.artifacts.diggingClaws]
					digSpeedBonus = 32
					toolTier = 2

				[gamerules.modded.player.artifacts.eternalSteak]
					cooldown = 15
					enabled = false

				[gamerules.modded.player.artifacts.everlastingBeef]
					cooldown = 15
					enabled = false

				[gamerules.modded.player.artifacts.feralClaws]
					attackSpeedBonus = 50

				[gamerules.modded.player.artifacts.fireGauntlet]
					fireDuration = 8

				[gamerules.modded.player.artifacts.flamePendant]
					cooldown = 0
					doGrantFireResistance = true
					fireDuration = 10
					strikeChance = 40

				[gamerules.modded.player.artifacts.flippers]
					swimSpeedBonus = 100

				[gamerules.modded.player.artifacts.goldenHook]
					experienceBonus = 75

				[gamerules.modded.player.artifacts.heliumFlamingo]
					flightDuration = 8
					rechargeDuration = 15

				[gamerules.modded.player.artifacts.kittySlippers]
					enabled = true

				[gamerules.modded.player.artifacts.luckyScarf]
					fortuneBonus = 1

				[gamerules.modded.player.artifacts.nightVisionGoggles]
					enabled = true
					strength = 25

				[gamerules.modded.player.artifacts.noveltyDrinkingHat]
					drinkingDurationMultiplier = 30
					eatingDurationMultiplier = 60

				[gamerules.modded.player.artifacts.obsidianSkull]
					fireResistanceCooldown = 60
					fireResistanceDuration = 30

				[gamerules.modded.player.artifacts.onionRing]
					hasteDurationPerFoodPoint = 6
					hasteLevel = 2

				[gamerules.modded.player.artifacts.panicNecklace]
					cooldown = 0
					speedDuration = 8
					speedLevel = 1

				[gamerules.modded.player.artifacts.pickaxeHeater]
					enabled = true

				[gamerules.modded.player.artifacts.plasticDrinkingHat]
					drinkingDurationMultiplier = 30
					eatingDurationMultiplier = 60

				[gamerules.modded.player.artifacts.pocketPiston]
					knockbackStrength = 15

				[gamerules.modded.player.artifacts.powerGlove]
					attackDamageBonus = 4

				[gamerules.modded.player.artifacts.rootedBoots]
					doGrowPlantsAfterEating = true
					enabled = true
					hungerReplenishingDuration = 15

				[gamerules.modded.player.artifacts.runningShoes]
					doIncreaseStepHeight = true
					speedBonus = 20

				[gamerules.modded.player.artifacts.scarfOfInvisibility]
					enabled = true

				[gamerules.modded.player.artifacts.shockPendant]
					cooldown = 0
					doCancelLightningDamage = true
					strikeChance = 25

				[gamerules.modded.player.artifacts.snorkel]
					enabled = true
					isInfinite = false
					waterBreathingDuration = 15

				[gamerules.modded.player.artifacts.snowshoes]
					allowWalkingOnPowderSnow = true
					slipperinessReduction = 100

				[gamerules.modded.player.artifacts.steadfastSpikes]
					enabled = true
					knockbackResistance = 10

				[gamerules.modded.player.artifacts.superstitiousHat]
					lootingLevelBonus = 1

				[gamerules.modded.player.artifacts.thornPendant]
					cooldown = 0
					maxDamage = 6
					minDamage = 2
					strikeChance = 50

				[gamerules.modded.player.artifacts.umbrella]
					isGlider = true
					isShield = false

				[gamerules.modded.player.artifacts.universalAttractor]
					enabled = true

				[gamerules.modded.player.artifacts.vampiricGlove]
					absorptionChance = 100
					absorptionRatio = 20
					maxHealingPerHit = 1

				[gamerules.modded.player.artifacts.villagerHat]
					reputationBonus = 100

				[gamerules.modded.player.artifacts.whoopeeCushion]
					fartChance = 12

		[gamerules.modded.updates]
			doSeasonCycle = true
			fakeLavaSourceConversion = false
			fakeWaterSourceConversion = true

		[gamerules.modded.mobs]
			hordeMultiplying = false
			hordeStacking = true
			hunternibling = true
			ironGolemRegenPower = 4
			sunray = true

		[gamerules.modded.chat]
			"puffish_skills:announceNewPoints" = true

	[gamerules.chat]
		#Whether advancements should be announced in chat.
		announce_advancements = true
		#Whether command blocks should notify admins when they perform commands.
		command_block_output = true
		#Whether to log admin commands to server log.
		log_admin_commands = true
		#Whether the feedback from commands executed by a player should show up in chat. Also affects the default behavior of whether command blocks store their output text.
		send_command_feedback = true
		#Whether death messages are put into chat when a player dies. Also affects whether a message is sent to the pet's owner when the pet dies.
		show_death_messages = true

	[gamerules.spawning]
		#Whether phantoms can spawn in the nighttime.
		do_insomnia = false
		#Whether mobs should naturally spawn. Does not affect monster spawners.
		do_mob_spawning = true
		#Whether patrols can spawn.
		do_patrol_spawning = false
		#Whether wandering traders can spawn.
		do_trader_spawning = false
		#Whether wardens can spawn.
		do_warden_spawning = false

	[gamerules.player]
		#Whether the server should skip checking player speed when the player is wearing elytra. Often helps with jittering due to lag in multiplayer.
		disable_elytra_movement_check = false
		#Players respawn immediately without showing the death screen.
		do_immediate_respawn = false
		#Whether players can craft only those recipes that they have unlocked.
		do_limited_crafting = false
		#Whether the player should take damage when drowning.
		drowning_damage = true
		#Whether the player should take fall damage.
		fall_damage = true
		#Whether the player should take damage in fire, lava, campfires, or on magma blocks.
		fire_damage = true
		#Whether the player should take damage when inside powder snow.
		freeze_damage = true
		#Whether the player should keep items and experience in their inventory after death .
		keep_inventory = false
		#Whether the player can regenerate health naturally if their hunger is full enough (doesn't affect external healing, such as golden apples, the Regeneration effect, etc.)
		natural_regeneration = false
		#What percentage of players must sleep to skip the night.
		#Range: > -2147483648
		players_sleeping_percentage = 60
		#The number of blocks outward from the world spawn coordinates that a player spawns in when first joining a server or when dying without a personal spawnpoint. Has no effect on servers where the default game mode is Adventure.
		#Range: > -2147483648
		spawn_radius = 10
		#Whether players in spectator mode can generate chunks
		spectators_generate_chunks = true

	[gamerules.mobs]
		#Whether raids are disabled.
		disable_raids = false
		#Makes angered neutral mobs stop being angry when the targeted player dies nearby.
		forgive_dead_players = true
		#The maximum number of pushable entities a mob or player can push, before taking 6 (♥♥♥) entity cramming damage per half-second. Setting to 0 or lower disables the rule. Damage affects Survival-mode or Adventure-mode players, and all mobs but bats. Pushable entities include non-Spectator-mode players, any mob except bats, as well as boats and minecarts.
		#Range: > -2147483648
		max_entity_cramming = 24
		#Whether creepers, zombies, endermen, ghasts, withers, ender dragons, rabbits, sheep, villagers, silverfish, snow golems, and end crystals should be able to change blocks, and whether mobs can pick up items. When mobGriefing is disabled, piglins do not pick up gold ingots, but a player can still barter with them by using the item on the mob. Similarly, villagers do not pick up food items but can still breed until they run out of any food already in their inventory. This also affects the capability of zombie-like creatures like zombified piglins and drowned to pathfind to turtle eggs.
		mob_griefing = true
		#Makes angered neutral mobs attack any nearby player, not just the player that angered them. Works best if forgiveDeadPlayers is disabled.
		universal_anger = false

	[gamerules.updates]
		#Whether the daylight cycle and moon phases progress.
		do_daylight_cycle = true
		#Whether fire should spread and naturally extinguish
		do_fire_tick = true
		#Whether the weather can change naturally. The /weather command can still change weather.
		do_weather_cycle = true
		#How often a random block tick occurs (such as plant growth, leaf decay, etc.) per chunk section per game tick. 0 and negative values disables random ticks, higher numbers increase random ticks. Setting to a high integer results in high speeds of decay and growth. Numbers over 4096 make plant growth or leaf decay instantaneous.
		#Range: > -2147483648
		random_tick_speed = 3
		#Whether vines can spread to other blocks. Cave vines, weeping vines, and twisting vines are not affected.
		do_vines_spread = true
		#Whether new sources of lava are allowed to form.
		lava_source_conversion = false
		#The maximum number of snow layers that can be accumulated on each block.
		#Range: > -2147483648
		snow_accumulation_height = 1
		#Whether new sources of water are allowed to form.
		water_source_conversion = true

	[gamerules.drops]
		#Whether entities that are not mobs should have drops.
		do_entity_drops = true
		#Whether mobs should drop items and experience orbs.
		do_mob_loot = true
		#Whether blocks should have drops.
		do_tile_drops = true
		#Whether block loot is dropped by all blocks (false) or randomly (true) depending on how far the block is from the center of a block explosion (e.g. clicking a bed in dimensions other than the Overworld).
		block_explosion_drop_decay = true
		#Whether block loot is dropped by all blocks (false) or randomly (true) depending on how far the block is from the center of a mob explosion (e.g. Creeper explosion).
		mob_explosion_drop_decay = true
		#Whether block loot is dropped by all blocks (false) or randomly (true) depending on how far the block is from the center of a TNT explosion.
		tnt_explosion_drop_decay = false

	[gamerules.misc]
		#The maximum length of a chain of commands that can be executed during one tick. Applies to command blocks and functions.
		#Range: > -2147483648
		max_command_chain_length = 65536
		#Whether the debug screen shows all or reduced information; and whether the effects of F3+B (entity hitboxes) and F3+G (chunk boundaries) are shown.
		reduced_debug_info = false
		#Controls the maximum number of blocks changed when using /clone, /fill, or /fillbiome.
		#Range: > -2147483648
		command_modification_block_limit = 32768
		#Whether certain sound events are heard by all players regardless of location.
		global_sound_events = true

#Configs related to difficulty changes
[difficulty]
	#If the difficulty should be set on world load
	#If true difficulty changes in game will also be saved to the config
	set_difficulty = false
	#The difficulty to set if 'set_difficulty' is true, respects if the difficulty is locked or not for the world
	#Allowed Values: PEACEFUL, EASY, NORMAL, HARD
	difficulty = "NORMAL"
	#If true the world will be set to hardcore, difficultly will be set to hard independent to the 'difficulty' config
	#Setting it to hardcore auto locks the difficulty while this is true
	hardcore = false
	#If a world's difficulty should be locked when loaded, if world already is locked it can't be changed
	#If the global world difficulty is enabled it's set first
	lock_difficulty = false
	#If true the 'hardcore' setting is enforced
	#If false the 'hardcore' setting isn't checked against the setting of a world
	enforce_hardcore = true

#A collection of misc configs
[misc]
	#If gamerules should be saved to config on world unload
	save_gamerules = false
	#A comma separated list of commands to run on world join, @p is replaced with joining player name, command is run by the server
	#Example: default_commands = ["/tellraw @p [\"\",{\"text\":\"Hi \"},{\"text\":\"@p\",\"color\":\"aqua\"}]"]
	default_commands = ["/tellraw @p {\"translate\":\"login.message\",\"color\":\"gold\"}"]
	#If gamerules and settings only should be used as the defaults when creating a world
	#This will also block saving of changes to the config
	use_as_defaults_only = true

