
["Get New Curios Slot %"]
	#Range: 0 ~ 100
	"new slot probability" = 10

["Speed Force Particles"]
	"Show particles?" = false

["Get fragments by destroying Trinkets?"]
	"Get Fragments?" = false

["Amount of Trinket Slot Obtainable:"]
	#Range: 0 ~ 99
	"How many trinket slots?" = 2

["Disable FOV disable"]
	"Disable FOV disable?" = false

["Starting Trinket Slot quantity"]
	#Range: 0 ~ 99
	"How many Trinket Slots do you start with?" = 2

