
[pregnantbabies]
	#Maximum number of babies a pregnant could spawn
	"Maximum numbers of summonings pregnant can spawn" = 6.0
	#disable the ability entirely
	"Disable spawning of summonings" = false
	#Example: 80 meaning 20 percent of sucker spawing and 80 of bidys. (by setting to 100 no sucker willl spawn)
	"Bidy spawning percentage pool" = 50.0

[hunter]
	#Can also be turned off with griefing gamemode
	"Allows hunter to destroy fence or doors" = true
	"Allows hunter to hunt animals" = true
	"Allows hunter to life steal" = true
	#Hunters will usaully eat any dropped meat they find
	"Allows hunter to eat dropped food" = true
	#hunter will usaully fly and despawn from sunlight
	"Hunter soar off from sunlight" = false

[bomber]
	#bomber explosion radius
	"Bomber explosion in block area" = 6.0
	#bomber explosion damage
	"Explosion impact damage" = 6.0
	#bomber explosion goo effect duration (In ticks: 20 ticks = 1 second)
	"Explosion goo duration" = 400.0

[clogger]
	#Clogger will usaully not tolererate player cheesing in a fight
	"Will clogger dig away(despawn) from cowardice enemy?" = true

[suckers]
	#To disable/enable this machanic
	"allow chances for sucker to spawn with something riding on them" = true
	#Per sucker, what at what percentage it would spawn with something
	"chances for sucker to have mob spawn riding on them, upon spawning" = 15.0
	#Example: 80 meaning 20 percent of baby zombie spawning and 80 of bidys. (by setting to 100 no baby zombie will spawn)
	"Bidy spawning percentage pool" = 80.0

["Big sucker"]
	#default at 5
	"How many suckers spawn per Big Sucker?" = 5.0

["The Wolf"]
	#They usaully spawn blade like mobs to attack target
	"Can the wolf spawn stroms" = false
	#Somehow it cant be chnaged via attributes so here it is. (exclusively for this mob)
	"The wolf swinging attack Damage" = 8.0

["The Lechery"]
	#This has to do with world ore generation
	"Do Lechery spawn as ore blocks" = false

["The Dungeon"]
	#Can The Dungeon mob and its structures spawn in thiss world?
	"Enable or Disabling dungeons" = false

[bidy]
	#bidy explosion damage
	"Explosion impact damage" = 8.0
	#bidy explosion radius.
	"Explosion radius" = 6.0
	#bidy goo explosion effect durarion (In ticks: 20 ticks = 1 second)
	"Explosion goo duration" = 100.0

["The Possesive"]
	#Can The Posessive mob and its structures spawn in thiss world?
	"Enable or Disabling Ocean banks" = false

["The Rabidus"]
	#Per hit
	"Change of inflicting rabies" = 0.06

[wheezer]
	#amount of hit to pop it's pore rendering its ability useless
	"Wheezer spores hitpoints" = 5.0
	#how long the fumes stay in taget's body (in ticks)
	"Wheezer spore duration" = 300.0

["The Ordure"]
	#explosion
	"Ordure death explosion damage" = 20.0

["Skeeper/Somnolence"]
	#(In ticks: 20 ticks = 1 second)
	"how long typnomiasis last in ticks?" = 200.0
	#(In ticks: 20 ticks = 1 second)
	"how long sleepi walking last in ticks?" = 60.0

